language: ruby
rvm:
  - 2.0.0
bundler_args: --without development
env: DRIVER=poltergeist
before_script:
  - psql -c 'create database askalot_test;' -U postgres
  - gem install bundler
  - "cp config/database.yml.example config/database.yml"
  - "cp config/configuration.yml.example config/configuration.yml"
  - rake db:schema:load

addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: HyRVFkNdt443xYbORBdaOHq+jMyUiZSZtAkkNb55EOfA/G91vsjnOwrxd6EEN13SHSx06dn2Wmh98dzx5xRjb/+xqRrpdj5NrNRGMfjJ0bgDa51Wuz+UlDCyL0J6+niqgnOVpmdoTEa4c1IJFnMxE/bh2i3siyZMUKszo9Rtpd4=
services:
  - elasticsearch
