language: ruby
rvm:
  - 2.0.0
bundler_args: --without development
env: DRIVER=poltergeist
before_script:
  - psql -c 'create database askalot_test;' -U postgres
  - gem install bundler
  - "cp config/database.yml.example config/database.yml"
  - "cp config/configuration.yml.example config/configuration.yml"
  - rake db:schema:load

addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: mFWo5T9J2dcyET4vnqBX1yhiCvkTuJPFzHgiIN87MzrUrcxTkN6xFQDjngDQ/mT4tRpZFZgdl0JNmZCxlDsLXD6b4JvsDB38aIRUGo3OhttITI3f3OXXVIomV/JE8jXOvLZ/qXmt7es7pyrip3yKuyvXwUnaYKbk1lWqrHqnzPA=
services:
  - elasticsearch
