language: ruby
rvm:
  - 2.4.4

services:
    - postgresql

addons:
  chrome: stable
  postgresql: "9.6"

cache:
  - bundler: true

sudo: false
bundler_args: --without development

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb && sudo service elasticsearch restart

before_script:
  - export TZ='Europe/Bratislava'
  - "cp config/database.yml.example config/database.yml"
  - "cp config/configuration.yml.example config/configuration.yml"
  - RAILS_ENV=fiit_test bundle exec rake db:create
  - RAILS_ENV=fiit_test bundle exec rake db:structure:load DB_STRUCTURE=components/university/db/structure.sql
  - RAILS_ENV=edx_test bundle exec rake db:create
  - RAILS_ENV=edx_test bundle exec rake db:structure:load DB_STRUCTURE=components/mooc/db/structure.sql
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - RAILS_ENV=fiit_test bundle exec rake rspec:test
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.fiit.json
  - RAILS_ENV=fiit_test bundle exec rake rspec:test_failed
  - RAILS_ENV=fiit_test bundle exec rake rspec:test_failed
  - RAILS_ENV=edx_test bundle exec rake rspec:test
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.edx.json
  - RAILS_ENV=edx_test bundle exec rake rspec:test_failed
  - RAILS_ENV=edx_test bundle exec rake rspec:test_failed

after_script:
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  - ./cc-test-reporter upload-coverage
