language: ruby
rvm:
  - 2.4.1

services:
  - elasticsearch

addons:
  chrome: stable
  postgresql: "9.3"
  code_climate:
    repo_token:
      secure: "qGGKazOsim5RO1DKsmX6llrLgAsD8O15M07DPqlqq+YBb1ApRTf5bTvG43qYM9SeUIjg3F112WPw42gYHNB+avPBv/AB54S5mr595t/xqeDylTeEQGCHTf/UlWX2FtXem7BL7TDx8g+iXh84VVoMFJHMLntNP+KtALOwcgPw6IbT9sHfhoEqqW8rwylhsdFDUbQDXiy1f9SWOTEMGNpmwu4DBGtjHMHQlJWdtnFagPAobuD93i61y2+rTJv8NTDsLt4EH3TpqXgXD3RUqz9t+sVNyvr/wkdzJE2+AR8VZCUWFuAmUz1y76dVKU1k8yN+ajk6sU9Xf+qfoDV7pEp2am4LX4uuWav1nvN+QBWsirsPuQKrhE4pokNkLMexGvYwdinMcVvYSWpPSK6eh36AWRxVzmC1MD0Czb8KDuDMJVDuLaZYNiLNDXlHrCkVtB9RIV9psjKxF+ntQPocVNd6IxNqHBkO4YiZxlc3ltc26ML9QYjJo0u+xUFhVqvbfU7I1tgmmxt1Us56mBT8RVyXqWpE/rEv1HKHtdzZXQpVPJgjAjuSYh2Cm3f1ziMiJNSyraeoiNeTeehZDQqAunbnpTIaCbl8KNUBm0BKb0HdZU5cC99g8YsSN+H5QIc8dbBQuyPJIpfufTfDSH79LYgidxXsbLw9xYEDN8eC03Zf/fU="

cache:
  - bundler: true

sudo: false
bundler_args: --without development

before_install:
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb && sudo service elasticsearch restart

before_script:
  - export TZ='Europe/Bratislava'
  - gem install bundler
  - "cp config/database.yml.example config/database.yml"
  - "cp config/configuration.yml.example config/configuration.yml"
  - RAILS_ENV=fiit_test bundle exec rake db:create
  - RAILS_ENV=fiit_test bundle exec rake db:structure:load DB_STRUCTURE=components/university/db/structure.sql
  - RAILS_ENV=edx_test bundle exec rake db:create
  - RAILS_ENV=edx_test bundle exec rake db:structure:load DB_STRUCTURE=components/mooc/db/structure.sql

script:
  - RAILS_ENV=fiit_test bundle exec rake rspec:test
  - RAILS_ENV=fiit_test bundle exec rake rspec:test_failed
  - RAILS_ENV=edx_test bundle exec rake rspec:test
  - RAILS_ENV=edx_test bundle exec rake rspec:test_failed

after_success:
  - bundle exec codeclimate-test-reporter
